# Generated by Django 3.0 on 2020-03-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='club_name',
        ),
    ]
